import Image from "next/image";
export const metadata = {
    title: "Login | My App",
    description: "Generated by create next app",
};

export default function Page() {
    return (
        <>
            <div className='w-full h-screen flex justify-center items-center'>
                <div className='w-3xl mx-auto p-5 shadow'>
                    
                </div>
            </div>
        </>
    );
}
